services:
    lexxpavlov.sonata.admin.settings_categories:
        class: Lexxpavlov\SettingsBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, model_class: Lexxpavlov\SettingsBundle\Entity\Category, manager_type: orm, group: "Settings", label: "Categories", translation_domain: "messages", icon: '<i class="fas fa-wrench"></i>' }
        calls:
            - [ setTranslationDomain, ['messages']]
            - [ setSettings, ['@Lexxpavlov\SettingsBundle\Service\Settings']]

    lexxpavlov.sonata.admin.settings:
        class: Lexxpavlov\SettingsBundle\Admin\SettingsAdmin
        tags:
            - { name: sonata.admin, model_class: Lexxpavlov\SettingsBundle\Entity\Settings, manager_type: orm, group: "Settings", label: "Settings", translation_domain: "messages", icon: '<i class="fas fa-wrench"></i>' }
        calls:
            - [ setTranslationDomain, ['messages']]
            - [ setSettings, ['@Lexxpavlov\SettingsBundle\Service\Settings']]
